version: '3'
services:
    postgres:
        image:  postgres:13.2-alpine
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=todo-dev
        ports: 
            - 5432:5432
        
    pgadmin:
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=mobile333t@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=0000
        ports: 
            - "5050:80"